create table employee_sales_dataset (
employee_id	varchar(35),
first_name	varchar(35),
last_name	varchar(35),
age number,
gender	varchar(35),
blood_group varchar(35),
email	varchar(35),
phone	varchar(35),
city	varchar(35),
state_	varchar(35),
region	varchar(35),
pincode	number,
department varchar(35),
position_	varchar(35),
shift	varchar(35),
education	varchar(35),
experience_years	number,
salary number,
bonus	number,
tax_deduction	number,
net_salary	number,
emp_status	varchar(35),
join_date	date,
last_promotion date,
performance_score number,
attendance_pct	number,
leaves_taken	number,
order_id	varchar(35),
order_date	date,
product_name varchar(35),	
category_	varchar(35),
quantity	number,
unit_price number,
discount_pct number,
revenue number,
tax_amount number,
net_revenue	number,
order_status varchar(35),
payment_mode varchar(35),	
delivery_days	number,
customer_rating	number,
return_flag	varchar(35),
customer_id	varchar(35),
customer_segment varchar(35),
sales_target	number,
sales_achieved number,
target_achieved	varchar(35),
manager_id	varchar(35),
team_size	number,
training_hours number,	
certifications number
);

drop table employee_sales_dataset;


